In [2]:
import os
import pandas as pd
import re

# Especifica la ruta de la carpeta
carpeta = './Data/'

# Lista todos los archivos en la carpeta y filtra los que terminan en .csv
archivos_csv = [archivo for archivo in os.listdir(carpeta) if archivo.endswith('.csv')]

# Imprime los nombres de los archivos CSV
for archivo in archivos_csv:
    print(archivo)

# Lista todos los archivos CSV en la carpeta
archivos_csv = [archivo for archivo in os.listdir(carpeta) if archivo.endswith('.csv')]

for archivo in archivos_csv:
    # Crear un nombre válido para la variable eliminando caracteres no permitidos
    nombre_variable = 'df_' + re.sub(r'\W+', '_', os.path.splitext(archivo)[0])
    
    # Construir la ruta completa del archivo
    ruta_completa = os.path.join(carpeta, archivo)
    
    # Leer el CSV y asignarlo a la variable dinámica
    globals()[nombre_variable] = pd.read_csv(ruta_completa)
    
    # Opcional: imprimir el nombre de la variable creada
    print(f"Variable creada: {nombre_variable}")

PV2D_AdditionalInfo.csv
PV2D_CalculationParameters.csv
PV2D_DataContainer.csv
PV2D_DicomInformation.csv
PV2D_FieldData_filtered.csv
PV2D_Patient.csv
Variable creada: df_PV2D_AdditionalInfo
Variable creada: df_PV2D_CalculationParameters
Variable creada: df_PV2D_DataContainer
Variable creada: df_PV2D_DicomInformation
Variable creada: df_PV2D_FieldData_filtered
Variable creada: df_PV2D_Patient

In [4]:
df_PV2D_FieldData_filtered

,Id,Data_ContainedType,Data_CountTotal,Data_Elements,Data_DimensionCount,Data_CountX,Data_CountY,Data_CountZ,Data_ReferenceX,Data_ReferenceY,...,GantryAngleCorrectionEnergy,IsIntegral,ModificationsIndex,ChangeHistory,IntegralGantryAnglesInfo,IsIsocenter,DistanceToIsocenter,IsocenterPosition,InPhantomRotation,IsExtractedPlane
0,BF6B0782-A9F7-4D89-B795-0005D3657170,System.Double,1024,b'\x00\x01\x00\x00\x00\xff\xff\xff\xff\x01\x00...,2,32,32,0,-118.0945,-118.0945,...,6,True,0,NaN,209.77 209.73 209.75 209.82 209.73 209.76 209....,False,0.0,NaN,0,False
1,8142949D-22C7-4A07-B111-001E83981DE0,System.Double,1024,b'\x00\x01\x00\x00\x00\xff\xff\xff\xff\x01\x00...,2,32,32,0,-118.0945,-118.0945,...,0,True,0,"3/1/2025 18:35 sbianchini: Rescale: 1,0150¥6/1...",NaN,False,0.0,NaN,0,False
2,EE8EA67C-FDD3-449A-922D-005AECC5F7C7,System.Double,1024,b'\x00\x01\x00\x00\x00\xff\xff\xff\xff\x01\x00...,2,32,32,0,-118.0945,-118.0945,...,0,True,0,NaN,179.82 179.82 179.82 179.81 179.82 179.81 179....,False,0.0,NaN,0,False
3,E9E3DBA7-6433-49AC-A636-00BB23F70159,System.Double,1024,b'\x00\x01\x00\x00\x00\xff\xff\xff\xff\x01\x00...,2,32,32,0,-118.0945,-118.0945,...,6,True,0,NaN,180.10 180.13 180.11 180.10 180.11 180.13 180....,False,0.0,NaN,0,False
4,867FC52E-04B2-469A-A62E-00C015B59F75,System.Double,1024,b'\x00\x01\x00\x00\x00\xff\xff\xff\xff\x01\x00...,2,32,32,0,-118.0945,-118.0945,...,6,True,0,NaN,179.94 179.94 179.97 179.95 179.95 179.97 179....,False,0.0,NaN,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
588,1F120594-699E-4D1F-A040-FC9628C1C52B,System.Double,1024,b'\x00\x01\x00\x00\x00\xff\xff\xff\xff\x01\x00...,2,32,32,0,-118.0945,-118.0945,...,6,True,0,NaN,212.02 212.00 211.99 212.02 212.05 212.04 212....,False,0.0,NaN,0,False
589,569A20F6-B53B-4169-AE95-FCE85002752C,System.Double,1024,b'\x00\x01\x00\x00\x00\xff\xff\xff\xff\x01\x00...,2,32,32,0,-118.0945,-118.0945,...,0,True,0,NaN,NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN Na...,False,0.0,NaN,0,False
590,F0771926-C370-42DD-A69A-FD249F3B202B,System.Double,1024,b'\x00\x01\x00\x00\x00\xff\xff\xff\xff\x01\x00...,2,32,32,0,-118.0945,-118.0945,...,6,True,0,NaN,329.80 329.81 329.77 329.80 329.80 329.81 329....,False,0.0,NaN,0,False
591,E5E64FE0-532F-47F8-AE9F-FEEBA711DFA3,System.Double,1024,b'\x00\x01\x00\x00\x00\xff\xff\xff\xff\x01\x00...,2,32,32,0,-118.0945,-118.0945,...,6,True,0,NaN,30.00 29.96 29.97 30.00 29.98 29.97 29.99 29.9...,False,0.0,NaN,0,False
592,3077DF75-180E-43B6-B7EB-FEF11EFE2F44,System.Double,1024,b'\x00\x01\x00\x00\x00\xff\xff\xff\xff\x01\x00...,2,32,32,0,-118.0945,-118.0945,...,6,True,0,NaN,54.89 54.87 54.89 54.92 54.91 54.88 54.88 54.8...,False,0.0,NaN,0,False

In [5]:
df_PV2D_DataContainer

,Id,ParentId,Name,Comment,ReportComment,ReportCheckupStateIndex,CreatedAt,CreatedBy,LastChangedAt,LastChangedBy,Discriminator
0,36991296-57CC-4E2D-90ED-000056862B5E,9FB53B70-14E6-49F8-9D12-015E620B27C0,Frame 00073,NaN,NaN,0,2024-09-04 11:42:38.110539,sdestri,2024-09-04 12:01:20.786805,sdestri,NaN
1,3B7B1A02-F869-454E-9D9D-0000666A87B3,CC6442EF-AFD4-4828-98B4-D524357FF8FB,Measurement,NaN,NaN,0,2024-04-26 16:13:45.824443,sbianchini,2024-04-26 16:13:45.971451,sbianchini,NaN
2,BDC5070D-671E-43FE-85BF-0001C7C4D9BA,B476CB59-B038-4B9F-8787-F7F4B4B4D4A9,Frame 01558,NaN,NaN,0,2025-01-16 17:49:20.656327,rlapera,2025-01-16 18:03:11.765865,rlapera,NaN
3,D0CDE884-DCA3-416D-AC15-0001D1960C76,B08224EF-CA70-4FD5-8F15-DC63A85327DA,Frame 00426,NaN,NaN,0,2024-05-17 19:01:45.217531,sdestri,2024-05-17 19:05:19.681214,sdestri,NaN
4,F9DAB511-E6CA-454D-9CAE-00021C58A9A6,057943CA-2EBF-41F7-9B19-E40C4D321B14,Frame 01085,NaN,NaN,0,2024-12-03 18:40:39.008150,rlapera,2024-12-03 18:42:33.604865,rlapera,NaN
...,...,...,...,...,...,...,...,...,...,...,...
120868,C27161A5-5A1E-4FA5-B865-FFFB56889F75,82980BBF-6C3F-402E-8E84-E73DEBA0419E,Frame 00200,NaN,NaN,0,2024-09-04 10:57:19.327527,sdestri,2024-09-04 11:01:05.066910,sdestri,NaN
120869,45637EC4-FCFD-47B0-B0DA-FFFBAFD6C445,7EAC63F0-01C4-4DC7-AAC2-7F21757F1882,Frame 00855,NaN,NaN,0,2024-09-04 09:35:34.560344,sdestri,2024-09-04 09:42:46.332003,sdestri,NaN
120870,CF57C64D-022A-4293-9F08-FFFD404CA82A,1A1F3C47-5D93-4674-B494-A9CC03ABB478,Frame 00893,NaN,NaN,0,2024-10-15 09:05:10.867605,sbianchini,2024-10-15 09:06:06.084416,sbianchini,NaN
120871,68BDC1A7-0E9A-44D7-8DE0-FFFDAEA9A477,52700C98-CDFC-487D-8E03-DBC779BCC972,Frame 02689,NaN,NaN,0,2024-11-08 18:00:52.265742,sdestri,2024-11-08 18:03:15.125070,sdestri,NaN
120872,A9856E1B-3F00-4520-A439-FFFFD4D917F1,5176DAA3-835E-4374-9D48-0002625867A9,Frame 00165,NaN,NaN,0,2024-11-08 18:12:11.151827,sdestri,2024-11-08 18:14:19.981865,sdestri,NaN

In [9]:
df_merge = pd.merge(df_PV2D_FieldData_filtered, df_PV2D_DataContainer, on='Id', how='left')

In [ ]:
df_merge.head()  # Muestra las primeras filas del DataFrame resultante

,Id,Data_ContainedType,Data_CountTotal,Data_Elements,Data_DimensionCount,Data_CountX,Data_CountY,Data_CountZ,Data_ReferenceX,Data_ReferenceY,...,ParentId,Name,Comment,ReportComment,ReportCheckupStateIndex,CreatedAt,CreatedBy,LastChangedAt,LastChangedBy,Discriminator
0,BF6B0782-A9F7-4D89-B795-0005D3657170,System.Double,1024,b'\x00\x01\x00\x00\x00\xff\xff\xff\xff\x01\x00...,2,32,32,0,-118.0945,-118.0945,...,6C28475F-B875-4A65-9556-28073BBF3704,Integral 30/01/2024 11:09:49.32,NaN,NaN,0,2024-01-30 11:15:53.752875,sdestri,2024-01-30 11:18:22.897553,sdestri,NaN
1,8142949D-22C7-4A07-B111-001E83981DE0,System.Double,1024,b'\x00\x01\x00\x00\x00\xff\xff\xff\xff\x01\x00...,2,32,32,0,-118.0945,-118.0945,...,A1F39C55-DC0D-4833-8158-1633FC178AAC,MX-QAR-VMDmLNmBOOSTVMAT,NaN,NaN,0,2025-01-03 17:14:36.482146,sbianchini,2025-01-06 11:59:30.021048,sbianchini,NaN
2,EE8EA67C-FDD3-449A-922D-005AECC5F7C7,System.Double,1024,b'\x00\x01\x00\x00\x00\xff\xff\xff\xff\x01\x00...,2,32,32,0,-118.0945,-118.0945,...,CC4A7E09-7840-4AC3-A793-296B61139E2F,Integral 06/06/2024 17:41:47.31,NaN,NaN,0,2024-06-06 17:50:09.248318,sdestri,2024-06-06 17:54:52.705178,sdestri,NaN
3,E9E3DBA7-6433-49AC-A636-00BB23F70159,System.Double,1024,b'\x00\x01\x00\x00\x00\xff\xff\xff\xff\x01\x00...,2,32,32,0,-118.0945,-118.0945,...,2A223D9F-815B-4B65-A601-CF9D642A96F8,MX RX2A QAR,NaN,NaN,0,2024-10-24 18:18:24.166222,rlapera,2024-10-24 19:13:19.119024,rlapera,NaN
4,867FC52E-04B2-469A-A62E-00C015B59F75,System.Double,1024,b'\x00\x01\x00\x00\x00\xff\xff\xff\xff\x01\x00...,2,32,32,0,-118.0945,-118.0945,...,14920707-059E-46A1-A5CA-CF67F8A5FE94,Integral 10/04/2024 17:20:04.14,NaN,NaN,0,2024-04-10 17:21:27.147519,dtolabin,2024-04-10 17:26:33.511261,dtolabin,NaN

In [12]:
df_merge.tail()

,Id,Data_ContainedType,Data_CountTotal,Data_Elements,Data_DimensionCount,Data_CountX,Data_CountY,Data_CountZ,Data_ReferenceX,Data_ReferenceY,...,ParentId,Name,Comment,ReportComment,ReportCheckupStateIndex,CreatedAt,CreatedBy,LastChangedAt,LastChangedBy,Discriminator
588,1F120594-699E-4D1F-A040-FC9628C1C52B,System.Double,1024,b'\x00\x01\x00\x00\x00\xff\xff\xff\xff\x01\x00...,2,32,32,0,-118.0945,-118.0945,...,C462966D-227E-4374-9DF1-066B804E710A,MX RX4A QAR 2DA MEDICION,NaN,NaN,0,2024-07-25 18:23:21.991724,rlapera,2024-07-25 18:31:31.189562,rlapera,NaN
589,569A20F6-B53B-4169-AE95-FCE85002752C,System.Double,1024,b'\x00\x01\x00\x00\x00\xff\xff\xff\xff\x01\x00...,2,32,32,0,-118.0945,-118.0945,...,0BC1BCDE-3617-4031-AD0C-A7E83A8D11A9,Integral 28/02/2025 09:22:23.51,NaN,NaN,0,2025-02-28 09:23:28.953984,dtolabin,2025-02-28 11:20:11.250785,dtolabin,NaN
590,F0771926-C370-42DD-A69A-FD249F3B202B,System.Double,1024,b'\x00\x01\x00\x00\x00\xff\xff\xff\xff\x01\x00...,2,32,32,0,-118.0945,-118.0945,...,960B92EF-F57B-4E1C-9C93-F48594954E9B,Integral 15/08/2024 23:14:16.21,NaN,NaN,0,2024-08-15 23:20:05.340558,dtolabin,2024-08-15 23:22:33.607035,dtolabin,NaN
591,E5E64FE0-532F-47F8-AE9F-FEEBA711DFA3,System.Double,1024,b'\x00\x01\x00\x00\x00\xff\xff\xff\xff\x01\x00...,2,32,32,0,-118.0945,-118.0945,...,386B2162-BC79-4DEA-80A3-F1E5423545E2,MX_QAR_RXA_VenaCava,NaN,NaN,0,2025-04-21 15:29:44.219787,dromero,2025-04-21 15:31:57.734372,dromero,NaN
592,3077DF75-180E-43B6-B7EB-FEF11EFE2F44,System.Double,1024,b'\x00\x01\x00\x00\x00\xff\xff\xff\xff\x01\x00...,2,32,32,0,-118.0945,-118.0945,...,21320C28-DB06-4018-A191-085044331D61,Integral 10/12/2024 21:06:39.36,NaN,NaN,0,2024-12-10 21:10:16.244824,dtolabin,2024-12-10 21:13:04.866657,dtolabin,NaN

In [13]:
df_PV2D_FieldData_filtered.shape

(593, 41)

In [14]:
df_merge.shape

(593, 51)

In [19]:
df_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 593 entries, 0 to 592
Data columns (total 51 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Id                              593 non-null    object
 1   Data_ContainedType              593 non-null    object
 2   Data_CountTotal                 593 non-null    int64
 3   Data_Elements                   593 non-null    object
 4   Data_DimensionCount             593 non-null    int64
 5   Data_CountX                     593 non-null    int64
 6   Data_CountY                     593 non-null    int64
 7   Data_CountZ                     593 non-null    int64
 8   Data_ReferenceX                 593 non-null    float64
 9   Data_ReferenceY                 593 non-null    float64
 10  Data_ReferenceZ                 593 non-null    float64
 11  Data_SpacingX                   593 non-null    float64
 12  Data_SpacingY                   593 non-null    float64
 13  Data_SpacingZ                   593 non-null    float64
 14  GantryAngleNullable             571 non-null    float64
 15  SignalTypeIndex                 593 non-null    int64
 16  ReferenceRelativeValue          593 non-null    float64
 17  PlaneTypeIndex                  593 non-null    int64
 18  ImageTypeValue                  593 non-null    int64
 19  CalculationTypeIndex            0 non-null      float64
 20  ReferenceSignalImageId          0 non-null      float64
 21  CompareSignalImageId            0 non-null      float64
 22  ReferenceVersion                593 non-null    int64
 23  CompareVersion                  593 non-null    int64
 24  Version                         593 non-null    int64
 25  MeasurementFrameId              592 non-null    object
 26  MeasurementId                   574 non-null    object
 27  IsDicom                         593 non-null    bool
 28  BeamStatus                      593 non-null    int64
 29  GantryAngleCorrectionTableName  531 non-null    object
 30  GantryAngleCorrectionBqi        593 non-null    float64
 31  GantryAngleCorrectionEnergy     593 non-null    int64
 32  IsIntegral                      593 non-null    bool
 33  ModificationsIndex              593 non-null    int64
 34  ChangeHistory                   49 non-null     object
 35  IntegralGantryAnglesInfo        573 non-null    object
 36  IsIsocenter                     593 non-null    bool
 37  DistanceToIsocenter             593 non-null    float64
 38  IsocenterPosition               0 non-null      float64
 39  InPhantomRotation               593 non-null    int64
 40  IsExtractedPlane                593 non-null    bool
 41  ParentId                        593 non-null    object
 42  Name                            593 non-null    object
 43  Comment                         0 non-null      object
 44  ReportComment                   0 non-null      object
 45  ReportCheckupStateIndex         593 non-null    int64
 46  CreatedAt                       593 non-null    object
 47  CreatedBy                       593 non-null    object
 48  LastChangedAt                   593 non-null    object
 49  LastChangedBy                   593 non-null    object
 50  Discriminator                   0 non-null      float64
dtypes: bool(4), float64(15), int64(16), object(16)
memory usage: 220.2+ KB

In [20]:
df_merge.describe()  # Muestra estadísticas descriptivas del DataFrame resultante

,Data_CountTotal,Data_DimensionCount,Data_CountX,Data_CountY,Data_CountZ,Data_ReferenceX,Data_ReferenceY,Data_ReferenceZ,Data_SpacingX,Data_SpacingY,...,Version,BeamStatus,GantryAngleCorrectionBqi,GantryAngleCorrectionEnergy,ModificationsIndex,DistanceToIsocenter,IsocenterPosition,InPhantomRotation,ReportCheckupStateIndex,Discriminator
count,593.000000,593.0,593.000000,593.000000,593.0,593.000000,593.000000,593.0,593.000000,593.000000,...,593.000000,593.0,593.000000,593.000000,593.000000,593.0,0.0,593.0,593.0,0.0
mean,1383.084317,2.0,32.929174,32.564924,0.0,-118.373485,-118.435736,0.0,7.607838,7.607838,...,0.202361,0.0,0.611282,5.372681,0.033727,0.0,NaN,0.0,0.0,NaN
std,8744.274539,0.0,22.626858,13.756801,0.0,8.255187,5.324297,0.0,0.271810,0.271810,...,1.031363,0.0,0.209067,1.837410,0.492040,0.0,NaN,0.0,0.0,NaN
min,1024.000000,2.0,32.000000,32.000000,0.0,-311.000000,-178.094500,0.0,1.000000,1.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.0,NaN,0.0,0.0,NaN
25%,1024.000000,2.0,32.000000,32.000000,0.0,-118.094500,-118.094500,0.0,7.619000,7.619000,...,0.000000,0.0,0.683000,6.000000,0.000000,0.0,NaN,0.0,0.0,NaN
50%,1024.000000,2.0,32.000000,32.000000,0.0,-118.094500,-118.094500,0.0,7.619000,7.619000,...,0.000000,0.0,0.683000,6.000000,0.000000,0.0,NaN,0.0,0.0,NaN
75%,1024.000000,2.0,32.000000,32.000000,0.0,-118.094500,-118.094500,0.0,7.619000,7.619000,...,0.000000,0.0,0.683000,6.000000,0.000000,0.0,NaN,0.0,0.0,NaN
max,213961.000000,2.0,583.000000,367.000000,0.0,-97.594500,-88.094500,0.0,7.619000,7.619000,...,12.000000,0.0,0.683000,6.000000,8.000000,0.0,NaN,0.0,0.0,NaN

In [25]:
df_merge['Data_CountX'].value_counts().sort_index(ascending=False)
df_merge_matrixx = df_merge[df_merge['Data_CountY']==32]
df_merge_matrixx.shape

(592, 51)

In [27]:
df_merge_matrixx.head().to_csv('./Data/df_merge_matrixx_head.csv', index=False)